// Axxon OS Knowledge Base & Documentation Catalog
export const KNOWLEDGE_BASE_ARTICLES = [
  {
    id: "kb-quickstart",
    title: "Quickstart: Build & Launch an AI Chatbot in 3 Minutes",
    category: "Getting Started",
    tags: ["quickstart", "beginner", "no-code", "setup", "bot builder"],
    readTime: "3 min read",
    summary: "Step-by-step guide to naming your chatbot, adding your first FAQs, and testing it in real-time without writing code.",
    content: `### 1. Overview
Axxon OS allows any business owner or developer to build, train, and deploy an enterprise-ready AI chatbot in minutes.

### 2. Step 1: Open Bot Builder
- Navigate to your **Dashboard** and click the **My Chatbots** tab.
- Click the **+ Create New Bot** button.
- Give your chatbot a clear name (e.g., *Atlas Support Bot* or *Acme Store Assistant*).
- Optionally provide your website URL so your bot knows its company context.

### 3. Step 2: Add Knowledge Base FAQs
- In the FAQ Builder section, enter frequent customer questions and clear answers.
- *Tip:* Include common variations (e.g. pricing, delivery times, return policy, contact email).
- Add at least 3–5 FAQs to give your bot a solid knowledge foundation.

### 4. Step 3: Configure Fallback Contact & Launch
- Provide a fallback contact such as a WhatsApp link (\`https://wa.me/...\`), Telegram username, or support email (\`mailto:support@example.com\`).
- Click **Save & Launch Bot**.
- Test your chatbot immediately using the interactive preview widget.`,
  },
  {
    id: "kb-embed-guide",
    title: "Embedding the Chatbot Widget on WordPress, Shopify, React & HTML",
    category: "Integration",
    tags: ["embed", "widget", "html", "wordpress", "shopify", "react", "iframe", "javascript"],
    readTime: "4 min read",
    summary: "How to copy your chatbot script tag or iframe code and paste it into any website platform seamlessly.",
    content: `### 1. The Universal Script Tag
Every bot generated by Axxon OS provides a lightweight JavaScript snippet that creates a floating bottom-right chat widget:

\`\`\`html
<!-- Axxon OS Chatbot Widget -->
<script 
  src="https://your-domain.com/widget.js" 
  data-bot-id="YOUR_BOT_ID" 
  async>
</script>
\`\`\`

### 2. Platform Specific Instructions:
- **Custom HTML/Static Sites:** Paste the script tag right before the closing \`</body>\` tag in your HTML.
- **WordPress:** Install a header/footer plugin (or edit \`footer.php\`) and paste the snippet.
- **Shopify:** Navigate to *Online Store > Themes > Edit Code*, open \`theme.liquid\`, and paste before \`</body>\`.
- **Wix / Squarespace:** Use the *Custom Code* or *Embed Code* block with HTML mode.
- **React / Next.js:** Place the script in your root layout or use an \`<iframe>\` pointing to \`/bot/YOUR_BOT_ID\`.`,
  },
  {
    id: "kb-faq-ai-engine",
    title: "Understanding FAQ Matching & Gemini AI Fallback",
    category: "AI & Architecture",
    tags: ["faq", "matching", "gemini", "fallback", "tokens", "synonyms", "jaccard"],
    readTime: "5 min read",
    summary: "How Axxon OS uses natural language tokenization, synonym expansion, and Gemini AI fallback to achieve 99%+ accuracy.",
    content: `### Dual-Engine Response Pipeline
Axxon OS uses a two-tier architecture to guarantee lightning-fast, hallucination-free answers:

1. **Tier 1: Deterministic FAQ NLP Engine (< 50ms)**
   - Text is normalized (punctuation removed, lowercased, stemmed).
   - Stop words are filtered and synonyms are automatically expanded (e.g. *cost*, *fee*, *pricing*, *rate*).
   - Computes keyword coverage and Jaccard token similarity score.
   - If match score >= 0.28, your exact approved answer is returned instantly.

2. **Tier 2: Gemini AI Contextual Fallback**
   - If no direct FAQ match is found, your knowledge base is formatted into a strict system prompt for Gemini AI.
   - Gemini answers questions accurately using only facts from your knowledge base.
   - If the query is completely outside your knowledge base, the bot gracefully offers your configured fallback contact (WhatsApp, Email, Telegram).`,
  },
  {
    id: "kb-currency-pricing",
    title: "Multi-Currency Pricing & Live Crypto Payment Gateways",
    category: "Billing & Plans",
    tags: ["currency", "pricing", "crypto", "usdt", "btc", "eth", "sol", "billing", "conversion"],
    readTime: "3 min read",
    summary: "Overview of automatic currency conversion across 12 global currencies and decentralized on-chain crypto checkout.",
    content: `### 1. Supported Global Currencies
Axxon OS includes real-time live currency conversion across:
- **USD** ($), **EUR** (€), **GBP** (£), **CAD** ($), **AUD** ($), **JPY** (¥)
- **NGN** (₦), **GHS** (GH₵), **KES** (KSh), **ZAR** (R), **INR** (₹), **AED** (د.إ)

### 2. Decentralized Crypto Payments
- Instant automated on-chain payment detection for **USDT (TRC-20 & ERC-20)**, **Bitcoin (BTC)**, **Ethereum (ETH)**, and **Solana (SOL)**.
- Secure, non-custodial direct address generation with QR codes and copy-to-clipboard functionality.`,
  },
  {
    id: "kb-chat-logs-analytics",
    title: "Analyzing Chat Logs & Identifying Unanswered Customer Questions",
    category: "Analytics & Logs",
    tags: ["logs", "chat logs", "analytics", "match rate", "questions", "history", "insights"],
    readTime: "4 min read",
    summary: "How to inspect every visitor conversation, review match rates, and discover missing FAQs from user chat logs.",
    content: `### 1. Chat Log Tracking
Every customer question asked to your chatbot is automatically recorded in real-time in the \`chat_logs\` database.

### 2. Key Metrics Explained:
- **Total Messages:** The cumulative volume of conversations handled by your bot.
- **Match Rate (%):** The percentage of queries answered immediately by your knowledge base FAQs.
- **Unmatched Queries (Fallbacks):** Questions where the bot utilized Gemini AI or fallback contacts.
- **Top Questions:** The most frequent user questions ranked by frequency.

### 3. Turning Logs into New FAQs:
Reviewing unmatched chat logs is the fastest way to improve your bot! Click on any logged question, refine the answer, and add it directly to your bot's knowledge base.`,
  },
  {
    id: "kb-voice-audio",
    title: "Voice Dictation & Text-to-Speech Audio Readout",
    category: "Features",
    tags: ["voice", "speech", "tts", "microphone", "audio", "accessibility"],
    readTime: "2 min read",
    summary: "Using the browser SpeechRecognition API for hands-free voice prompting and Web Speech TTS for audio responses.",
    content: `### 1. Voice Input (Microphone)
- In the AI Assistant tab, click the **Microphone** button to speak your prompt aloud.
- Real-time speech transcription automatically converts your voice to text.

### 2. Audio Read Aloud (Text-to-Speech)
- Click the **Listen / Read Aloud** button on any AI response to have the browser speak the answer using natural voice synthesis.
- Click **Stop Voice** at any time to pause audio playback.`,
  },
  {
    id: "kb-white-label",
    title: "White-Labeling & Agency Branding Options",
    category: "Agency & Enterprise",
    tags: ["white-label", "branding", "agency", "custom logo", "theme"],
    readTime: "3 min read",
    summary: "How to customize colors, bot avatar, header titles, and remove 'Powered by Axxon' on King & Ultra plans.",
    content: `### 1. White-Label Features
Available on King (Annual) and Ultra (Lifetime) tiers:
- Custom chatbot header title and subtitle.
- Brand logo and custom bot avatar.
- Custom primary and secondary theme accent colors.
- Complete removal of platform watermarks.`,
  },
  {
    id: "kb-offline-persistence",
    title: "Offline Storage & Hybrid Database Synchronization",
    category: "Architecture",
    tags: ["database", "postgresql", "pg-mem", "storage", "persistence", "offline"],
    readTime: "3 min read",
    summary: "How Axxon OS synchronizes PostgreSQL data with disk JSON persistence for 100% zero data-loss durability.",
    content: `### Multi-Tier Storage Resilience
Axxon OS is engineered for 100% uptime:
- **Cloud Database Tier:** Full PostgreSQL connection pool when \`DATABASE_URL\` is provided.
- **Embedded In-Memory Engine:** Zero-dependency \`pg-mem\` instance with SQL functions.
- **Persistent Disk Journaling:** Automatic JSON disk synchronization to \`/data/persistent_storage.json\` after every mutation (INSERT, UPDATE, DELETE).`,
  }
];

export const GLOSSARY_TERMS = [
  {
    term: "Knowledge Base",
    category: "Glossary",
    plain: "The private library of facts, FAQs, and product details you provide so your bot knows how to answer your customers.",
    tech: "Structured document store & FAQ key-value pairs used for prompt grounding and deterministic NLP lookup.",
  },
  {
    term: "Chat Log",
    category: "Glossary",
    plain: "A recorded transcript of questions visitors have asked your chatbot, showing what was asked and when.",
    tech: "Persisted event logs containing query tokens, timestamps, bot IDs, and Boolean match status.",
  },
  {
    term: "Fallback",
    category: "Glossary",
    plain: "The backup safety message (or WhatsApp/email link) shown when the bot encounters a question it hasn't been taught.",
    tech: "Default handling route when NLP similarity is below threshold and secondary generative inference is ungrounded.",
  },
  {
    term: "AI Tokens",
    category: "Glossary",
    plain: "Small building blocks of words (about 4 characters) that AI models read and write to formulate sentences.",
    tech: "Sub-word vector embeddings processed by the Transformer attention matrix.",
  },
  {
    term: "Web Search Grounding",
    category: "Glossary",
    plain: "Allowing the AI to look up live information on Google so it can answer questions about today's events with source links.",
    tech: "Integration of Google Search tool in the GenAI model config returning verifiable URI citations in groundingChunks.",
  },
  {
    term: "Match Rate",
    category: "Glossary",
    plain: "The percentage of customer questions that your bot answered instantly using your exact approved FAQs.",
    tech: "Ratio of matched query events over total chat_logs rows within a target date interval.",
  },
];
